### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by diziara** [mooeypoo/wikilookup-wordpress#8]
Default styling for the popup picks up the text color from the theme, but then sets a white background. On a dark skin, this leaves the text unreadable. Also, the default styling for the trigger word is a dark dashed line, which is nearly unnoticeable on a dark skin.

Suggested solutions: Either set the text to black in the popup by default instead of inheriting from the skin, or make it easy for users to configure it to match their theme (either settings, or documented css classes they can edit themselves). The text decoration for the trigger word should either inherit the body text color from the theme, or it should be user configurable in settings or with a documented css class.

**Comment by mooeypoo** [comment]
Added dark mode support in v1.1.2

You rock, thanks for the suggestion and testing!
